# Configurações do Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Versões (Minecraft 1.21.1)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Mod
mod_version=1.0.0
maven_group=com.hideclan
archives_base_name=hideclan

# Dependências
fabric_version=0.116.0+1.21.1
